django-commons/drf-excel

drf_renderer_xlsx/renderers.py

This feature enables the usage of serializers that contain nested objects, such as:
```javascript
{
"name": "John", 
"age": 28, 
"location": {
"city": "Philadelphia", 
"country": "United States"
}
}
```
Which will then translate into the XLSX file column names:
```
[ name | age | location.city | location.country ]
```
This feature will improve the support for Model relations with Foreign Keys

Add support for dictionary nested values

---

drf_renderer_xlsx/renderers.py

From my viewpoint it's required to return lists also as a separated list.
If possible please take the change to next release so that i can use it via pip in my project :-)

Added iterables in flatten to item list

---

drf_renderer_xlsx/renderers.py

this is basically a workaround if someone uses nested fields (e.g. `HyperlinkWrapperField()`) and doesn't want to use a different serializer for xlsx export.
This fix prevents a `TypeError` on  `items.append((new_key, list_sep.join(v)))`

write array of array as json

---

drf_renderer_xlsx/renderers.py

The `XLSXRenderer` is referencing `v[0]` before checking if `v[0]` exists. The PR adds a length check to avoid an IndexError when empty arrays are the value of a field after serialization.

Fix IndexError on empty Iterable fields

---

drf_renderer_xlsx/mixins.py

Applying the `XLSXFileMixin` to a view set also applies the mixin to any additional created actions. It is possible for these actions to return Django `HttpResponse` objects instead of Django Rest Framework `Response` objects. This PR prevents an error from occurring when a raw `HttpResponse` object is returned.
Example action that returns an HttpResponse:
```python
@action(detail=True, methods=['get'])
def qr(self, request, *args, **kwargs):
"""
Return a QR code png image.
"""
response = HttpResponse(content_type='image/png')
return response
```
Without this fix, accessing this endpoint will result in an `AttributeError: 'HttpResponse' object has no attribute 'accepted_renderer'`.

Fix bug with Mixin applying to HttpResponse 

---

drf_renderer_xlsx/renderers.py

`join` cannot be used with non string values

converting values to str during flattening

---

drf_renderer_xlsx/renderers.py

When serialising, we iterate through the headers we find in the first result:
```
elif isinstance(results, ReturnList) or type(results) is list:
column_names_first_row = self._flatten(results[0])
```
Let's say the response looks like this:
```
{
results: [
{
title: 'Example 1',
some_relation: {
id: 1,
title: 'I am a relation'
},
some_value: 100
},
{
title: 'Example 2',
some_relation: null,
some_value: 200
}
]
}
```
This will lead to the headers `title, some_relation.id, some_relation.title, some_value`. While this works for the first result, the second row will have less values and therefore shift `some_value` to the left, ending up in the column of `some_relation.title`, with the one most right being empty.
A second problem would be when the second result in the example would actually be …

Fixed bugs when serialising nested serializers

---

drf_renderer_xlsx/renderers.py

Currently, when using nested fields (when using a serializer instead of a field) the header of those fields is displayed as their key representation even though xlsx_use_labels is set to True and the serializers fields have labels defined.
Passing these parameters to the recursive call fixes this problem and displays the nested fields labels.

Pass label_sep and use_labels to recursive call

---

drf_renderer_xlsx/renderers.py

a case of CSV injections have become public/popular in mainstream media here. This PR sanitizes field values by prepending `'` in front of possible malicious code. xlsx readers handle these values as strings 
Tested with MS Excel, Numbers and LibreOffice.
`ESCAPE_CHARS` are taken from https://owasp.org/www-community/attacks/CSV_Injection

Escape possible malicious chars

---

drf_renderer_xlsx/renderers.py

When rendering, it lets determine if the data is **dict** or **list**.
(Previously, it checks if it is **ReturnDict** or **ReturnList**)
This change allows the renderer to use user-generated data.
ex)
```
data = {'a': 'Apple'}
XLSXRenderer().render(data=data)
```

Change the data type checked by the renderer

---

drf_renderer_xlsx/renderers.py

I think it is different between header "Repoter Header" and table_sheet "Report sheet" 
```ptython
def get_header(self):
return {"use_header": False, "tab_title": "test"}
```
generally, sheet is necessary but header is not 
this commit is a backwards compatible manner 
thanks,

feat: split table_title and header_title

---

drf_excel/fields.py

- using drf date field format to parse datetime/date/time when provided (over REST_FRAMEWORK global setting)
- fixes #55

Take DRF date field format over global REST_FRAMEWORK when provided

---

README.md
drf_excel/renderers.py
drf_excel/utilities.py

Added support for sheet view options, things like `showGridLines`, `showRuler`, `rightToLeft` etc.
see https://openpyxl.readthedocs.io/en/stable/_modules/openpyxl/worksheet/views.html#SheetView for a list of options

support for sheet view options

---

drf_excel/renderers.py

There is a new drf release https://www.django-rest-framework.org/community/release-notes/#3140 
Here `NullBooleanField` is no longer available and so I removed the one reference to allow support for drf 3.14.0
It was also not required as the `isinstance(field, BooleanField)` would return true for a `NullBooleanFIeld` due to object inheritance:
```python
>>> from rest_framework.fields import NullBooleanField
>>> field = NullBooleanField()
>>> from rest_framework.fields import BooleanField
>>> isinstance(field, BooleanField)
True
>>> 
```
So I think we should be good :+1:
Thank you for the package :heart: @FlipperPA

Remove usage of depreciated NullBooleanField for drf 3.14.0

---

drf_excel/renderers.py

according to https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` should be used. Closes #60

Set correct media type

---

drf_excel/mixins.py

Use django's own escape_uri_path to fix the problem of Chinese filenames not being downloaded
使用django自带的escape_uri_path修复中文文件名无法下载的问题

bugfix:Fix the problem that non-English file names cannot be downloaded

---

drf_excel/renderers.py

Fixes https://github.com/wharton/drf-excel/issues/73 
The proposed solution:
- replaces the call to `save_virtual_wookbook` by its non-deprecated version `save_wookbook`. 
- migrates the logic previously implemented in `save_virtual_wookbook` from openpyxl to this repository. 
- replaces the usage of `TemporaryFile` by `NamedTemporaryFile` as suggested by the openpyxl author on its deprecation message.

fix save_virtual_workbook deprecation/removal in openpyxl 3.1.0

---

drf_excel/renderers.py

Hi there,
Thanks for creating & maintaining `drf-excel` 😃 
I'm running `drf` on `Windows Server 2019 (Datacenter)` for legacy/historical reasons.  This version blocks `NamedTemporaryFile` from saving to temp dir.  
> https://stackoverflow.com/questions/23212435/permission-denied-to-write-to-my-temporary-file
`TemporaryFile` seems to work fine across platforms in its place as it is not blocked by the dreaded permissions

fix(windows): replace NamedTemporaryFile with TemporaryFile

---

drf_excel/renderers.py

Thank you for developing such an excellent plugin. I have found that when encountering django lazy loading, an error will be reported. The following example can reproduce this problem:
```python
from django.db import models
from django.utils.translation import gettext_lazy as _
class MyModel(models.Model):
STATUS_CHOICES = (
('Created', _('Created')),
('Processing', _('Processing')),
('Finished', _('Finished')),
)
status = models.CharField(choices=STATUS_CHOICES)
...
from rest_framework import serializers
class MySerializers(serializers.ModelSerializer):
status_display = serializers.CharField(source='get_status_display')
class Meta:
model = MyModel
fields = ('status', 'status_display')
```
Only use `gettext_ Lazy` only has this issue, and `gettext` does not. I have analyzed that the …

fix support django lazy property

---

.pre-commit-config.yaml
drf_excel/fields.py
drf_excel/mixins.py
drf_excel/renderers.py

Add Ruff to pre-commit config for linting and formatting

---

pyproject.toml
tests/settings.py
tests/test_viewset_mixin.py
tests/testapp/models.py
tests/testapp/serializers.py
tests/testapp/views.py
tests/urls.py

Following up from https://github.com/wharton/drf-excel/pull/87 to add more test coverage

Add test covering a viewset using XLSXFileMixin

---

drf_excel/renderers.py
tests/conftest.py
tests/test_renderers.py
tests/test_viewset_mixin.py
tests/testapp/models.py
tests/testapp/serializers.py
tests/testapp/views.py
tests/urls.py
tox.ini

Results from my branch here: https://app.codecov.io/gh/browniebroke/drf-excel/tree/test-coverage-renderers

Increase test coverage for renderers.py

---

pyproject.toml

Getting an error when trying to upload as it stands:
```
ERROR HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
'Framework :: Django :: 5' is not a valid classifier. See https://packaging.python.org/specifications/core-metadata for more information.
```
Looks like we need to specify the major and minor versions now: https://pypi.org/classifiers/

Fix Django classifiers

---

README.md

fix for [that issue](https://github.com/wharton/drf-excel/issues/98)
Fix #98

fix pagination issue

---

drf_excel/renderers.py
tests/test_viewset_mixin.py
tests/testapp/models.py
tests/testapp/serializers.py
tests/testapp/views.py
tests/urls.py

I noticed that my `write_only` fields were trying to render in the final excel. This fix should solve that problem. Also couldn't resist leaving the docstring.

Enhance nested serializer handling by skipping write_only fields.

---

.github/workflows/release.yml
.github/workflows/test.yml
pyproject.toml
uv.lock

As we were using a dynamic version, we couldn't migrate until recently due to https://github.com/astral-sh/uv/issues/7533
This has now been resolved in https://github.com/astral-sh/uv/pull/10622, released in uv v0.15.9

Migrate to uv for packaging

---

pyproject.toml
tox.ini

Django 5.2 is due to be released in a few weeks: https://thib.me/django-packages-already-on-5-2

Add support for Django 5.2
